language: java
jdk:
- oraclejdk8
script:
- cd config/ && gradle build && cd ../ 
- cd discovery/ && gradle build && cd ../
- cd gateway/ && gradle build && cd ../
- cd book-service/ && gradle build && gradle jacocoTestReport && cd ../
after_success:
- bash <(curl -s https://codecov.io/bash)
