version: "2.1"
services:
  config:
    image: config:1
    ports:
      - "8083:8083"
    networks:
      - inet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/config/default"]
      interval: 10s
      timeout: 10s
      retries: 5
  discovery:
    image: discovery:1
    depends_on:
      config:
        condition: service_healthy
    networks:
      - inet
    ports:
      - "8082:8082"
  gateway:
    image: gateway:1
    ports:
      - "8080:80"
    networks:
      - inet
    depends_on:
      - discovery
  book-service:
    image: book-service:1
    networks:
      - inet
    depends_on:
      - discovery
networks:
  inet: