version: '2.1'
services:
  config:
    image: config:4
    ports:
      - '8083:8083'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/config/default"]
      interval: 10s
      timeout: 10s
      retries: 5
  discovery:
    image: discovery:2
    depends_on:
      config:
        condition: service_healthy
    links:
      - config
    ports:
      - '8082:8082'
  gateway:
    image: gateway:2
    ports:
      - '8080:8080'
    depends_on:
      - discovery
    links:
      - discovery
      - config
  book-service:
    image: book-service:3
    links:
      - discovery
      - config
      - gateway
