version: "3"
services:
  config:
    image: config:1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8083:8083"
    networks:
      - inet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/config/default"]
      interval: 10s
      timeout: 10s
      retries: 5
  discovery:
    image: discovery:1
    deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
    depends_on:
      - config
    networks:
      - inet
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 10s
      timeout: 10s
      retries: 5
  gateway:
    image: gateway:1
    deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
    ports:
      - "80:8080"
    networks:
      - inet
    depends_on:
      - discovery
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
  book-service:
    image: book-service:1
    deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
    networks:
      - inet
    depends_on:
      - discovery
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/"]
      interval: 10s
      timeout: 10s
      retries: 5
networks:
  inet: